
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    'plan',
    {
      type: 'category',
      label: 'Chapters',
      items: ['chapter2', 'chapter3'],
    },
    {
      type: 'category',
      label: 'AI Robot Brain',
      items: [{
        type: 'autogenerated',
        dirName: 'ai-robot-brain',
      }],
    },
    {
      type: 'category',
      label: 'Digital Twin',
      items: [{
        type: 'autogenerated',
        dirName: 'digital-twin',
      }],
    },
    {
      type: 'category',
      label: 'Robotic Nervous System',
      items: [{
        type: 'autogenerated',
        dirName: 'robotic-nervous-system',
      }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'specification',
        'tasks',
        'sp.constitution',
        'sp.implement',
        'sp.plan',
        'sp.specify',
        'sp.task',
      ],
    },
  ],
};

module.exports = sidebars;
